City-of-Helsinki/mvj-ui

src/components/collapse/Collapse.js, src/components/collapse/_collapse.scss, src/leases/components/leaseSections/tenant/OtherTenantItem.js, src/leases/components/leaseSections/tenant/OtherTenantItemsEdit.js, src/leases/components/leaseSections/tenant/Tenant.js, src/leases/components/leaseSections/tenant/TenantItemsEdit.js, src/leases/helpers.js
Close collapse by default if tenant is not active
=> Show gray background for tenants which are not active.

src/components/form/_form.scss, src/components/multi-select/_multi-select.scss
Fine-tuned focus styles on all field components
=> Fine-tuned react-select and react-multiselect styles

src/app/App.js, src/components/collapse/Collapse.js, src/components/commentPanel/CommentPanel.js, src/components/content/_content.scss, src/components/form/FormField.js, src/components/form/_form.scss, src/components/table/_table.scss, src/components/topNavigation/TopNavigation.js, src/components/topNavigation/_top-navigation.scss, src/contacts/components/ContactsListPage.js, src/leases/components/LeaseListPage.js, src/leases/components/leaseSections/leaseArea/PlanUnitItem.js, src/leases/components/leaseSections/leaseArea/PlanUnitItemsEdit.js, src/leases/components/leaseSections/tenant/TenantItem.js, src/leases/helpers.js, src/rentbasis/components/RentBasisListPage.js
Squashed commits:
[3c990f6] Show field always at the bottom on form field container. Show error on absolute position
[02eb4ab] Added transition to close icon for menu icon when opening menu
[283c79a] Don't set isResizing state on collapse component if component is unmounted
[fe14520] Fixed bug which prevented comment panel to open
[0ebc5dc] Fixed decimal number format on "Laskun hallintaosuus" field on Tenants tab
[f466f8c] Disabled active page from pagination to prevent unnecessary loading when clicking link
[e9713f2] Fixed function to get address on lease list page
=> Fixed table row hover color (+7 squashed commits)

src/components/table/SortableTable.js, src/invoices/helpers.js, src/leases/components/leaseSections/invoice/InvoicePanel.js, src/leases/components/leaseSections/invoice/InvoiceTableAndPanel.js, src/leases/components/leaseSections/invoice/InvoiceTemplate.js, src/leases/components/leaseSections/invoice/forms/EditInvoiceForm.js, src/leases/components/leaseSections/rent/BasicInfo.js, src/leases/components/leaseSections/rent/BasicInfoEdit.js, src/leases/constants.js, src/leases/helpers.js
Fix sorting of table in case that columns changes
Added seasonal start and end dates to rents
Select number of due dates from predefined options
=> Show number (not id) field as invoice number

Dockerfile, README.md, docker-compose.yml
=> Add docker env setup

src/invoices/helpers.js
Changed invoice.id to payment.id for payments edit
=> correct id for payments

src/landUseContract/attributes-mock-data.json, src/leaseStatisticReport/components/LeaseInvoicingConfirmationReport.js, src/leases/components/leaseSections/contract/ContractItemEdit.js, src/leases/components/leaseSections/rent/BasisOfRent.js, src/leases/components/leaseSections/rent/BasisOfRentEdit.js, src/leases/components/leaseSections/rent/BasisOfRentManagementSubventionEdit.js, src/leases/components/leaseSections/rent/BasisOfRentTemporarySubventionEdit.js, src/leases/enums.js, src/leases/helpers.js
Subvention percentages with cumulative calculations
=> Subventions

src/plotSearch/components/plotSearchSections/basicInfo/BasicInfo.js, src/plotSearch/components/plotSearchSections/basicInfo/BasicInfoEdit.js, src/plotSearch/enums.js, src/plotSearch/helpers.js
Relies on https://github.com/City-of-Helsinki/mvj/pull/355 .
=> Add search class field to plot searches

.env.example
* Updated some env variables to make developing this software a bit easier
=> Updated example env variables

src/api/callApi.js, src/api/callApiAsync.js, src/api/callUploadRequest.js, src/api/constants.js
This interface is only available in Finnish anyway, so this will make it more consistent whenever any entries have been translated.
=> Set Finnish as the default language for requests

src/enums.js, src/main.scss, src/plotApplications/actions.js, src/plotApplications/components/PlotApplication.js, src/plotApplications/components/PlotApplicationEdit.js, src/plotApplications/components/infoCheck/PlotApplicationApplicantInfoCheck.js, src/plotApplications/components/infoCheck/PlotApplicationApplicantInfoCheckModal.js, src/plotApplications/components/infoCheck/PlotApplicationInfoCheckCollapse.js, src/plotApplications/components/infoCheck/PlotApplicationInfoCheckForm.js, src/plotApplications/components/infoCheck/PlotApplicationTargetInfoCheck.js, src/plotApplications/components/infoCheck/_plotApplicationInfoCheckCollapse.scss, src/plotApplications/enums.js, src/plotApplications/helpers.js, src/plotApplications/reducer.js, src/plotApplications/requests.js, src/plotApplications/saga.js, src/plotApplications/selectors.js, src/plotApplications/spec.js, src/plotApplications/types.js
External service integration is still pending.
=> Enable editing of base applicant information check data

src/leases/components/leaseSections/rent/BasisOfRent.js
Add parantheses around the calculator type check to fix the issue
=> Fix issue of not showing saved subventions

jsconfig.json, src/enums.js, src/plotApplications/actions.js, src/plotApplications/components/PlotApplication.js, src/plotApplications/components/PlotApplicationEdit.js, src/plotApplications/components/infoCheck/PlotApplicationApplicantInfoCheck.js, src/plotApplications/components/infoCheck/PlotApplicationApplicantInfoCheckForm.js, src/plotApplications/components/infoCheck/PlotApplicationApplicantInfoCheckModal.js, src/plotApplications/components/infoCheck/PlotApplicationInfoCheckCollapse.js, src/plotApplications/components/infoCheck/PlotApplicationTargetInfoCheck.js, src/plotApplications/components/infoCheck/_plotApplicationInfoCheckCollapse.scss, src/plotApplications/enums.js, src/plotApplications/helpers.js, src/plotApplications/reducer.js, src/plotApplications/requests.js, src/plotApplications/saga.js, src/plotApplications/selectors.js, src/plotApplications/spec.js, src/plotApplications/types.js
Implemented as part of the application view screen; a later PR will reorganise both the view and edit screens.
=> Add target info check functionality

src/leases/components/leaseSections/leaseArea/CustomDetailedPlan.js, src/leases/components/leaseSections/leaseArea/CustomDetailedPlanEdit.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteCustomDetailedPlan.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteEditCustomDetailedPlan.js
Taiga issue \#1729. Quite a trivial issue, the only thing to check really is whether I actually caught all the places where this needed to be changed.
=> Change build permission unit labels from sqm to floor-sqm

src/api/createUrl.js, src/components/button/Button.js, src/components/file/FileDownloadButton.js, src/components/form/DocumentsButton.js, src/components/form/FieldTypeCheckbox.js, src/components/form/FormField.js, src/components/form/normalizers.js, src/components/form/validations.js, src/components/modal/Modal.js, src/components/modal/ModalButtonWrapper.js, src/components/table/SortableTable.js, src/leases/components/leaseSections/invoice/forms/CollectionLetterTotalRow.js, src/leases/components/leaseSections/invoice/forms/CreateCollectionLetterForm.js, src/main.scss, src/plotApplications/actions.js, src/plotApplications/components/PlotApplication.js, src/plotApplications/components/exportModal/PlotSearchExportModal.js, src/plotApplications/components/exportModal/PlotSearchExportModalTargetTable.js, src/plotApplications/components/exportModal/_PlotSearchExportModal.scss, src/plotApplications/reducer.js, src/plotApplications/requests.js, src/plotApplications/saga.js, src/plotApplications/selectors.js, src/plotApplications/spec.js, src/plotApplications/types.js, src/plotSearch/components/PlotSearchPage.js, src/plotSearch/components/plotSearchSections/basicInfo/BasicInfo.js
The exact location of the export button might still have to be discussed, but all the functionality is there now.
=> Add plot application export modal

src/components/form/FieldTypeFractional.js, src/components/form/FieldTypeHidden.js, src/components/form/FormField.js, src/components/form/_form.scss, src/enums.js, src/plotApplications/components/PlotApplicationSectionData.js, src/plotApplications/components/PlotApplicationSubsection.js, src/plotApplications/helpers.js, src/plotSearch/components/plotSearchSections/application/ApplicationPreviewSection.js, src/plotSearch/types.js
Added support for form field default value.
=> Implemented hidden and fractional field type.

src/leases/components/leaseSections/leaseArea/CustomDetailedPlan.js, src/leases/components/leaseSections/leaseArea/CustomDetailedPlanEdit.js, src/leases/components/leaseSections/leaseArea/PlanUnitItem.js, src/leases/enums.js, src/leases/helpers.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteCustomDetailedPlan.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteEdit.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSitePlanUnit.js
TESTING:
- At least plan unit 91-11-327-9 has usage distributions
- use feature-plan-unit-usagedistribution be-branch for testing
=> Added usage distributions to plan units.

src/plotApplications/actions.js, src/plotApplications/components/PlotApplicationPage.js, src/plotApplications/reducer.js, src/plotApplications/saga.js, src/plotApplications/selectors.js, src/plotApplications/spec.js, src/plotApplications/types.js, src/plotSearch/components/PlotSearchPage.js, src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchApplicationsOpeningSection.js
Previously the page just kept loading endlessly if the application couldn't be loaded for any reason.
=> Fix plot application page error states

src/application/components/ApplicationAnswersField.js, src/plotSearch/components/plotSearchSections/application/ApplicationPreviewSection.js
Depends on https://github.com/City-of-Helsinki/mvj/pull/592
=> Fix fieldtype mapping after removal of FieldType in backend

src/application/helpers.js, src/areaSearch/actions.js, src/areaSearch/components/AreaSearchApplication.js, src/areaSearch/components/AreaSearchApplicationEdit.js, src/areaSearch/components/AreaSearchApplicationListPage.js, src/areaSearch/components/AreaSearchApplicationPage.js, src/areaSearch/reducer.js, src/areaSearch/spec.js, src/areaSearch/types.js, src/types.js
Enables adding and removing of attachments to and from area search applications by the Helsinki city official.
=> Area search application: add and remove attachments in officer UI

src/leases/components/leaseSections/rent/RentAdjustmentEdit.js, src/leases/helpers.js
Fixes this issue: https://helsinkisolutionoffice.atlassian.net/browse/MVJ-7
=> Fix removing rent adjustment

src/leases/helpers.js
The "Määrä" was not updating properly when editing rent adjustments in the Vuokraukset => Vuokrat tab. Here are the fixes.
=> fix checking changes in subventions

src/components/modal/_modal.scss, src/leases/components/createLease/CreateLeaseForm.js
Remove lease filter from Luo vuokraustunnus modal field "Liittyy vuokraukseen".
=> Related lease in create lease: remove service unit filter

src/components/topNavigation/_top-navigation.scss
=> top nav title button: keep items in one line

package.json, src/app/App.tsx, src/app/_app.scss, src/components/topNavigation/TopNavigation.tsx, src/components/topNavigation/_top-navigation.scss, yarn.lock
The new usergroup list looks as follows. It is toggled using the info icon. I could not find a person icon and the icons are created in the mvj-ui as manually inserted vector values, so it would take extra work to make it into a person icon. Is info icon good enough in your opinion?
=> toggleable usergroup list

src/leases/helpers.ts
change is matching change in API
Related to https://github.com/City-of-Helsinki/mvj/pull/655
=> change lease ordering fields

.env.example, src/auth/auth.spec.ts, src/auth/constants.ts, src/auth/reducer.ts, src/auth/selectors.ts, src/auth/useAuth.ts, src/util/storage.ts
Please note that the target branch is `hds-login`
=> Configure Keycloak

src/contacts/components/ContactReadonly.tsx, src/contacts/components/ContactsListPage.tsx, src/contacts/components/forms/ContactForm.tsx, src/contacts/components/templates/ContactTemplate.tsx, src/contacts/enums.ts, src/contacts/types.ts
see ticket for screenshots.
Related: https://github.com/City-of-Helsinki/mvj/pull/762
=> show contacts leases in contact list & page

src/contacts/helpers.ts
Should fix the issue of service_unit showing with contact data (Tenants)
=> add service_unit to getContentContact

src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndex.tsx, src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndexEdit.tsx, src/leases/enums.ts
Enable info balls (ui data) and cleaning up the enums.
=> tasotarkistus: info balls

src/components/file/FileDownloadButton.tsx, src/components/file/FileDownloadLink.tsx
Pass filescan error messages to user. Added a long timeout so that user has time to read it.
Might require more changes but not sure yet.
=> MVJ-131 ClamAV (UI)

src/leaseStatisticReport/components/LeaseInvoicingConfirmationReport.tsx
Create a link to leases from the reports.
Related backend changes: https://github.com/City-of-Helsinki/mvj/pull/849
=> reports: link to leases

src/leaseStatisticReport/components/LeaseInvoicingConfirmationReport.tsx
Statistic report, link to lease column changes:
- open in new tab
- unset margin and border to match the spacing of other cells
=> Mvj 642 reports link to lease new tab and styling

package.json, src/auth/selectors.ts, src/auth/types.ts, src/components/file/FileDownloadButtonHDS.tsx, src/creditDecision/components/CreditDecisionSearchPage.tsx, src/creditDecision/components/SanctionsCheckForm.tsx, src/creditDecision/components/SanctionsCheckRequest.tsx, src/creditDecision/components/SanctionsCheckTemplate.tsx, src/creditDecision/enums.ts, src/usersPermissions/enums.ts, yarn.lock
Implemented this without redux or redux-forms as this is completely independent form intended to make a direct get request to API to download a file, and not do anything with the response.
Made the components functional, and used HDS instead of mvj-ui components. This page now contains two forms with different mechanisms and styles, but it doesn't really bother I would assume. It will showcase also how HDS could work, and how it would look like in mvj-ui.
Did not try to make this perfect, since it is mainly a selector between two requests, person or a companys sanctions check. Any obvious issues or improvements would be good to hear about.
src/components/file/FileDownloadButtonHDS.tsx
is a copy of DownloadButton, but with HDS button implemented, and some other small changes.
Screenshots …
=> Mvj 659 sanctions check

src/leases/components/search/Search.tsx
The corresponding API PR: https://github.com/City-of-Helsinki/mvj/pull/863
Screenshots in the MVJ-585 ticket.
=> MVJ-585 - Add leasing search filter for preparer's own leases

src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndex.tsx, src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndexEdit.tsx, src/leases/components/leaseSections/rent/RentItem.tsx, src/leases/components/leaseSections/rent/RentItemEdit.tsx, src/leases/enums.ts, src/leases/helpers.ts
Add new field to Rent: start_price_index_point_figure_year.
Corresponding API PR: https://github.com/City-of-Helsinki/mvj/pull/871
=> MVJ-610 Tasotarkistus index point figure update

src/areaSearch/components/AreaSearchApplication.tsx, src/areaSearch/components/AreaSearchApplicationEdit.tsx, src/areaSearch/components/_area-search-application.scss, src/areaSearch/types.ts
in areasearch application and applicationedit
adds information about `is_user_helsinki_ad`
=> change areasearchattachments component to hds table

src/components/form/FieldTypeIntendedUseSelect.tsx
in order to fetch all intended uses
=> increase limit for FieldTypeIndendedUseSelect

src/areaSearch/components/AreaSearchApplication.tsx, src/areaSearch/components/AreaSearchApplicationEdit.tsx, src/areaSearch/enums.ts, src/areaSearch/types.ts, src/leases/components/createLease/CreateLeaseForm.tsx, src/leases/enums.ts, src/leases/helpers.ts, src/leases/saga.ts, src/leases/types.ts, src/plotSearch/enums.ts
Set area search status to "settled" and set settled_date when lease is created. Also, create a link between area search and lease.
Related API PR: https://github.com/City-of-Helsinki/mvj/pull/901
=> MVJ-841 Area search changes when lease is created

src/areaSearch/enums.ts, src/auditLog/helpers.ts
The UI part is just digging the translations from attributes.
Related API PR: https://github.com/City-of-Helsinki/mvj/pull/902
=> MVJ-634 - Register AreaSearchStatus to auditlog

src/areaSearch/components/AreaSearchApplicantInfoCheckWithAttributes.tsx, src/areaSearch/components/AreaSearchApplicantInfoCheckWithAttributesEdit.tsx, src/areaSearch/components/AreaSearchApplication.tsx, src/areaSearch/components/AreaSearchApplicationAnswersField.tsx, src/areaSearch/components/AreaSearchApplicationAnswersSection.tsx, src/areaSearch/components/AreaSearchApplicationCreateForm.tsx, src/areaSearch/components/AreaSearchApplicationEdit.tsx, src/areaSearch/components/AreaSearchApplicationPage.tsx, src/areaSearch/components/AreaSearchApplicationSubsection.tsx, src/areaSearch/components/_area-search-applicant-info-check.scss, src/areaSearch/components/_area-search-application-answers-section.scss, src/areaSearch/components/infoCheck/AreaSearchApplicantInfoCheck.tsx, src/areaSearch/components/infoCheck/AreaSearchApplicantInfoCheckEdit.tsx, src/areaSearch/components/infoCheck/AreaSearchApplicantInfoCheckEditItem.tsx, src/areaSearch/components/infoCheck/AreaSearchApplicantInfoCheckForm.tsx, src/areaSearch/components/infoCheck/AreaSearchApplicantInfoCheckModal.tsx, src/areaSearch/constants.ts, src/areaSearch/enums.ts, src/areaSearch/helpers.ts, src/areaSearch/types.ts, src/contacts/actions.ts, src/contacts/components/ContactModal.tsx, src/contacts/types.ts, src/main.scss
This change enables the user to create a contact from an area search application.
=> MVJ-865 create contact from area search

src/leases/components/leaseSections/contract/ContractItem.tsx, src/leases/components/leaseSections/contract/ContractItemEdit.tsx, src/leases/enums.ts, src/leases/helpers.ts
Add executor field to contracts and contract changes.
Related API changes: https://github.com/City-of-Helsinki/mvj/pull/930
=> MVJ-850 executor field

src/components/button/Button.tsx, src/tradeRegister/components/Search.tsx, src/tradeRegister/components/TradeRegisterSearchPage.tsx
TO DO: manual testing the PRH endpoint. I could not get it to work with the Virre configs I set for myself.
=> MVJ-883 Refactor trade register search into final-form

src/creditDecision/components/CreditDecisionHistory.tsx, src/creditDecision/components/CreditDecisionSearchPage.tsx, src/creditDecision/components/SearchForm.tsx
Here are refactorings of credit decision views from redux-form to final-form.
There is also a refactor from the old class syntax to the newer hook syntax, to make future changes easier.
=> MVJ-886: credit decision to final-form

src/leases/actions.ts, src/leases/components/leaseSections/summary/LeaseHistoryEdit.tsx, src/leases/helpers.ts, src/leases/types.ts
Thought this had some redux-form since it used to initialize a form, but turns out that initialize was not needed at all.
Intention was to migrate to final-form but nothing to migrate here after converting to functional component :/
=> Mvj 1013 lease summary history final form
