City-of-Helsinki/mvj-ui

src/leases/components/leaseSections/contract/ContractItemEdit.js

When inputting a contract number into a newly created contract, the page crashes because of the "is this contract in another lease already" (`leasesWithContractNumber`) check. This hotfix merely prevents crashing but also effectively disables the check for new contracts so it should be fixed properly later.

Ensure contract exists before accessing its member

---

src/enums.js
src/main.scss
src/plotSearch/components/plotSearchSections/basicInfo/BasicInfo.js
src/plotSearch/components/plotSearchSections/basicInfo/BasicInfoEdit.js
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSite.js
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteEdit.js
src/plotSearch/components/plotSearchSections/basicInfo/_basic-info.scss
src/plotSearch/enums.js
src/plotSearch/helpers.js
src/plotSearch/mock-data.json
src/plotSearch/saga.js
src/plotSearch/spec.js

Also includes the matching change for the `targets` -> `plot_search_targets` breaking change in the backend.

Add info links

---

src/plotApplications/actions.js
src/plotApplications/components/PlotApplication.js
src/plotApplications/components/PlotApplicationEdit.js
src/plotApplications/components/PlotApplicationSubsection.js
src/plotApplications/constants.js
src/plotApplications/helpers.js
src/plotApplications/reducer.js
src/plotApplications/saga.js
src/plotApplications/selectors.js
src/plotApplications/spec.js
src/plotApplications/types.js

- Target data sections can't be added or removed manually, they're generated automatically based on selected targets
- Metadata is attached to these sections, signifying the target they're related to
- This metadata is also used in the application inspection view to show the address and identifier of each related target

Control the root-level target sections based on selected targets

---

src/plotSearch/components/plotSearchSections/application/EditPlotApplicationSectionForm.js
src/plotSearch/components/plotSearchSections/application/SectionField.js
src/plotSearch/components/plotSearchSections/application/_application.scss
src/styles/_variables.scss

- Split content into smaller components, both to make them more digestable and to alleviate some performance issues due to constant thrashing of the modal content when anything changed
- Add a radio button for toggling subsection visibility
- Add support for hiding the add-multiple toggle if the template disallows setting it on
- Adjust colors, margins, indentation

Improve section editor modal

---

src/leaseStatisticReport/components/LeaseStatisticReportForm.js
src/leaseStatisticReport/components/LeaseStatisticReportPage.js

**1. Remove unecessary fixed title from LeaseStatisticReportForm.js**
When creating reports, the page always showed the "Vuokrausten tilastoraportti" as a title for the section, even though there
was something else selected as the report type.
Remove the title completely as we are showing the selected report title in the report output.
**2. LeaseStatisticReportForm: Render submit button based on report type**
Remove fixed value checks to determine which button (Luo raportti / Lähetä sähköpostiin) to show. Use the `is_async` from the API to render the correct form submit button for each report type.

Small fixes to lease statistic reports

---

README.md
src/plotApplications/components/PlotApplication.js
src/plotApplications/components/PlotApplicationSubsection.js
src/plotApplications/components/PlotApplicationsPage.js
src/plotApplications/constants.js
src/plotApplications/enums.js
src/plotApplications/helpers.js
src/plotApplications/types.js
src/plotSearch/types.js

- Subsections within the top level applicant section will or won't be shown based on the selected applicant type
- The primary identifying detail (personal identity number or company ID) is attached into the metadata object of the section
- This identifying detail is used to label the collapse section when the application is viewed
Also includes Flow typing fixes (mostly permanent, but also some stop-gap temporary Object fallbacks) to all involved files.

Add special handling for applicant type

---

src/leases/components/leaseSections/rent/BasisOfRent.js
src/leases/components/leaseSections/rent/BasisOfRentEdit.js
src/leases/components/leaseSections/rent/BasisOfRentManagementSubventionEdit.js
src/leases/components/leaseSections/rent/BasisOfRentTemporarySubventionEdit.js
src/leases/components/leaseSections/rent/BasisOfRentsEdit.js
src/leases/enums.js
src/leases/helpers.js
src/util/helpers.js

* Fix whitespace on some of the components
* formatNumber: Add optional visible decimals
* Add a new basis of rent calculator type
* BasisOfRentsEdit: Ignore the last profit margin percentage
* We don't want to copy the last profit margin percentage to a new calculator anymore. So use an empty object as the new calculator base.
* Update BasisOfRent calculation helper functions
* Update BasisOfRent components to include a new calculator type
* Include new calculator type "lease2022"
* When changing the calculator type, reset/clear all fields and remove subventions
* Update both the form component and the component that renders saved values
* Update discount values when currentAmountPerArea changes
* Add code comments and group constants to have a better understanding of the code
* Update …

New basis of rent calculator type and fixes to calculations

---

src/leases/components/leaseSections/rent/BasisOfRent.js
src/leases/components/leaseSections/rent/BasisOfRentEdit.js
src/leases/components/leaseSections/rent/MastChildrenEdit.js
src/leases/enums.js
src/leases/helpers.js

* Remove whitespace from `src/leases/enums.js`
* Fix issues in area unit and intended use
* Add missing `LEASE2022` check
*  Move checkbox fields to their own row
* Remove if clause from `locked_at` to always show `locked_at` field
* Fix copy to clipboard fields
* Use it only for the `LEASE` and `LEASE2022` types
* Update what fields are copied
* Add missing disabled attribute to fields with `locked_at`
* Fix rent titles
* Update `locked_at` text
* Sort basis of rent children by their id when fetching data

Fix basis of rent calculator issues

---

src/plotApplications/components/PlotApplication.js
src/plotApplications/components/PlotApplicationEdit.js
src/plotApplications/components/PlotApplicationSubsection.js
src/plotApplications/components/PlotApplicationsPage.js
src/plotApplications/helpers.js
src/plotApplications/requests.js
src/plotApplications/saga.js
src/plotApplications/types.js

- The path parameter is now put into use now that it's exposed and set by the backend. The path defines the exact position the file is contained in in the answer data, which allows each occurrence of a certain field object to have unique file lists (i.e. two targets can have different reference attachments).
- Many quirks when the user aborts an edit of the application have been cleaned up. Files that are removed in the editor will now actually only be deleted when the edit is submitted, and newly uploaded files will also only be linked to the field during the save. Would-be linked files from applications that were never finished and submitted will also no longer show up the next time a new application editor (possibly for an unrelated set of targets) is opened.

Improve plot application attachment handling

---

src/leaseStatisticReport/components/LeaseInvoicingConfirmationReport.js
src/leaseStatisticReport/enums.js
src/leaseStatisticReport/helpers.js
src/util/helpers.js

* Remove all hardcoded checks for different types of fields based on their name
* Use value formatting provided by the backend
* Use the correct table sort function based on the is_numeric boolean
Depends on https://github.com/City-of-Helsinki/mvj/pull/463

Remove hardcoded values from lease statistic reports

---

src/plotApplications/components/PlotApplicationCreate.js
src/plotApplications/components/PlotApplicationSectionData.js
src/plotApplications/helpers.js
src/plotSearch/helpers.js

N.B.: Custom detailed plan addresses won't show in the application list unless https://github.com/City-of-Helsinki/mvj/pull/475 is cherry-picked in the backend.

Fix application views to support custom detailed plans

---

src/plotSearch/components/plotSearchSections/application/_application.scss

If the first field of a second-level subsection (e.g. company details) was considered to open upwards towards the section header, it would get cut off. This change makes it visible in that uncommon case as well.

Fix hint text tooltip cutting off in some cases

---

src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchReservationRecipients.js

I made own branch for this small error, because no other fixes in this ui needed for fixing the issue1807 and this was the only I ended up doing.

Changed wrongly typed 'small' -parameter in Column element

---

src/components/address-search/AddressSearchInput.js

Previously, the address search field could not find address data so that it would show the street number. Moreover, it used several endpoints to search first for addresses, and if it could not find them, it used streets as a fallback. This fix makes the search results show the street number and the municipality, and simplifies the code by using only one endpoint. For this reason, a lot of logic is removed.

Fix address search input

---

src/application/components/ApplicationSubsection.js
src/application/constants.js
src/application/formValidation.js
src/application/spec.js
src/areaSearch/components/AreaSearchApplicationCreateForm.js
src/areaSearch/components/AreaSearchApplicationCreatePage.js
src/areaSearch/components/AreaSearchApplicationCreateSpecs.js
src/components/form/FieldTypeDatePicker.js
src/components/form/FieldTypeFractional.js
src/components/form/FormField.js
src/plotApplications/components/PlotApplicationCreate.js

Adds validators for select application form fields, and also fixes some area search specs page validations that were fixed on the public side earlier.

Plot search form validations

---

src/plotSearch/constants.js

Editing email identifier fields in the application editor should not be allowed.

prevent editing email identifier in application editor

---

src/plotSearch/components/PlotSearchListPage.js
src/plotSearch/components/search/Search.js

- Change redux-form names to match the backend
- Reflect the above in simple mode detection on pageload
- Add proper subtype handling (only show subtypes of selected type, clear subtype on type change, disable dropdown with no type selected)
Matching backend: https://github.com/City-of-Helsinki/mvj/pull/556

Fix plot search list page filtering

---

src/plotSearch/components/directReservationLinkModal/DirectReservationLinkModal.js

Code seems to intend to pick `target.custom_detailed_plan` if `target.plan_unit` does not exist. The code failed on `target.plan_unit` being falsy, so couldn't get the identifier.

Fix getting targetIdentifier if plan_unit falsy

---

src/plotSearch/components/plotSearchSections/application/EditPlotApplicationSectionFieldForm.js
src/plotSearch/helpers.js

API expects `default_value` to be of type string.
This ensures that all values are stringified.

Fix: stringify form field default_value for multiple selection feature

---

Dockerfile

Found this commit in another branch, the pipeline is failing due to debian strech package repos not being available any longer, so we can go with this.

Upgrade to newer node and nginx in the Dockerfile

---

src/application/components/infoCheck/ApplicantInfoCheckEdit.js
src/application/components/infoCheck/ApplicantInfoCheckForm.js
src/application/components/infoCheck/ApplicantInfoCheckModal.js
src/areaSearch/components/AreaSearchApplicantInfoCheckEdit.js

It would attempt to mark e.g. trade register check to all the applicants applications. This behavior is not desired in area search.

Hide show mark all in area search applicant info

---

src/areaSearch/components/AreaSearchApplicationAuditLog.js
src/areaSearch/components/AreaSearchApplicationPage.js
src/areaSearch/enums.js
src/areaSearch/types.js
src/auditLog/actions.js
src/auditLog/reducer.js
src/auditLog/saga.js
src/auditLog/selectors.js
src/auditLog/spec.js
src/auditLog/types.js

Pretty much duplicationg of the lease change history page.

Add change history to area search

---

src/application/components/ApplicationSubsection.js

This fixes the issue of area search application form not rendering properly in the mvj-ui, when creating an area search.

Fix field types to render area search application form

---

src/areaSearch/components/AreaSearchApplicationListPage.js

Don't filter area search applications by default

remove default service unit filter from area search application list page

---

src/leases/components/leaseSections/rent/RentAdjustmentEdit.js
src/leases/helpers.js

When a user adds a rent adjustment in Vuokraus => Vuokrat tab, and then tries to add a subvention, the subvention form does not open. The user needs to save the changes first, open the edit view again and then they could add a subvention. These changes fix that bug.
The problem was that the `subventionType` has been set from `null` to `""` when the user clicks the "Lisää subventio" button, which does not make the subvention form to open. The `componentDidUpdate` does not fire. Seems to be caused by type coercion. Now when the subvention form is opened, `subventionType` is set to `"unspecified"`, which works because it is truthy.
The value `"unspecified"` also makes the full amount recalculation to skip applying subvention values, which prevents changing the full amount to 0 when the …

Fix adding subventions for newly added rent adjustments

---

src/components/inputs/UserServiceUnitSelectInput.js
src/components/table/TableFilters.js
src/components/topNavigation/TopNavigation.js
src/leases/components/LeaseListPage.js
src/leases/components/search/Search.js

move service unit filter next to basic search in leases view

---

package.json
yarn.lock

I got the following error trying to run `develop` with `yarn start`, so I created these changes.
```code
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'fs/promises'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/home/jukka-ahonen/CustomerProjects/City-of-Helsinki/mvj-ui/node_modules/babel-loader/lib/cache.js:21:5)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load …
```

url polyfill for webpack 5

---

src/util/helpers.tsx
src/util/spec.ts

Please check if this makes sense, I encoutered errors on `vuokra-alue` page due to how this type was previously. I'm not sure how this changed, or if it was wrong to begin with

change type for formatDecimalNumber to take in string

---

src/leases/components/leaseSections/leaseArea/PlanUnitItem.tsx
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteCustomDetailedPlan.tsx
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteEdit.tsx
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSiteEditCustomDetailedPlan.tsx
src/plotSearch/components/plotSearchSections/basicInfo/PlotSearchSitePlanUnit.tsx
src/util/constants.ts
src/util/helpers.tsx
src/util/spec.ts

createPaikkatietovipunenUrl to createPTPPlanReportUrl and createPTPPlotDivisionUrl

MVJ-245_paikkatietovipunen-urls-broken-fix

---

src/api/callApiAsync.ts
src/api/types.ts
src/areaSearch/selectors.ts
src/batchrun/selectors.ts
src/components/form/FieldTypeIntendedUseSelect.tsx
src/components/form/FormField.tsx
src/contacts/requestsAsync.ts
src/contacts/types.ts
src/enums.tsx
src/leases/components/leaseSections/summary/Summary.tsx
src/leases/components/leaseSections/summary/SummaryEdit.tsx
src/leases/helpers.ts
src/leases/requestsAsync.ts
src/leases/types.ts
src/serviceUnits/types.ts
src/types.ts
src/util/helpers.tsx

this change filters intended use choices based on service_unit, adds and improves typing here and there
Related to API change: https://github.com/City-of-Helsinki/mvj/pull/657

fetch intended use choices from api & query with leases service_unit

---

src/components/form/FormField.tsx
src/leases/components/search/Search.tsx

utilizes choices loaded from metadata with OPTIONS lease/
Abandoned the idea of async fetching choices filtered by users selected serviceUnit. It seemed to require a lot more changes than seems worthwhile for this feature that might be used quite little.

add intended use filter for least list

---

src/leaseCreateCharge/requests.ts

Previously, receivable types (saamislaji) were filtered by user's active service unit in Vuokraus => Laskutus tab, both in the invoice edit view and create new invoice view. However, they should be filtered by the current lease's service unit in order to make sure that it is not possible to give a receivable type for the lease's invoice that belongs to a wrong service unit.
Notice that saving the changes to the invoice does not work. That issue will be handled separately.

invoice edit: fetch receivable types by lease's service unit

---

src/leases/components/leaseSections/invoice/InvoicePanel.tsx
src/leases/components/leaseSections/invoice/_invoice-panel.scss

Automatically generated invoices can't be edited. This change makes it clearer by preventing unnecessary saves with conditionally rendering the following error message and hiding the save button

error message and no save button for generated invoices edit view

---

src/leaseStatisticReport/requests.ts

Service unit query parameter was previously sent as single string like "1,2,3,4", which is not a proper input for forms.ModelMultipleChoiceField. Synchronous reports already handled this query string properly, so now email reports use the same query parameter parsing for service unit.

Properly split the query parameter for service unit in email reports

---

src/leases/components/leaseSections/constructability/SendEmailModal.tsx

I couldn't get the awesome-font icons to load in the send email modal. It should work, I just don't understand why not. Therefore, I made a bit of a different solution by using text instead of icons but I think it looks quite good like this as well.

fix icons in send email modal

---

src/leases/components/leaseSections/invoice/InvoicePanel.tsx

Fields of automatically generated invoices are mostly read only, but there are exceptions: payments and postpone_date.
For this reason, the warning text will be removed and the save button restored for generated invoices.

Remove automatically generated invoices not editable text and restore edit buttons

---

src/components/form/FormField.tsx

tried to render an object which is not possible as text.

fix intended use issue for readonly perms

---

.env.example
src/auth/constants.ts
src/auth/selectors.ts

avoid using boolean values in envvars as yaml, ansible, .env evaluate them differently

refactor sso provider selection

---

src/components/button/_close-button.scss

Fix the size props of the css class for the button. It also had a wrong icon, so I changed it to an X.
Fixes the bug in both on the Yhteenveto and the Laskutus tabs.

comment modal: fix size and icon of close button

---

src/api/callApiPaginated.ts
src/leaseCreateCharge/helpers.ts
src/leaseCreateCharge/requests.ts
src/leaseCreateCharge/saga.ts

The default limit for receivable_type/ request is 30, but there are more receivable types for AKV than 30. This change makes the request in the mvj-ui to make several requests in order to get all the available receivable types for the given service unit.

receivable types: fetch beyond page limit

---

src/leases/components/leaseSections/rent/BasicInfo.tsx
src/leases/components/leaseSections/rent/BasicInfoEdit.tsx
src/leases/helpers.ts
src/leases/types.ts

Sort due dates correctly in the UI. Currently they are not shown in correct order, sorting needs to be done first by month then by date

sorting for seasonal dueDates

---

src/leases/components/leaseSections/rent/BasicInfoEdit.tsx

Found that we had a sorting issue while editing, especially when inserting months. It moved the items inplace, e.g. very problematic when you intend to type `11` but it sorts it due to first change `1`.
Handling this with redux-form seemed cumbersome, so I think it makes sense to let the editable dueDates to be not sorted.
This PR also fixes some of the typing issues.

Fix seasonal rent duedate edit sorting

---

src/application/components/ApplicationSubsection.tsx
src/application/helpers.ts

If the radiobuttoninline field is 'hakija', the choices will be sorted by value so that Yritys is first and Henkilö is last.

Sort radionbuttoninline field choices

---

eslint.config.mjs

eslint gives an unnecessary error about missing React prop types.  For example,
```code
'fetchServiceUnits' is missing in props validation eslint[react/prop-types](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/prop-types.md)
```
This creates a lot of errors in the editor, making development and finding bugs harder. We don't use React's typing but that of TypeScript, so we can disable prop-types. TypeScript will still generate error for missing props.

remove prop type check

---

src/leases/components/LeaseListPage.tsx
src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndex.tsx
src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndexEdit.tsx
src/leases/components/leaseSections/rent/RentItem.tsx
src/leases/components/leaseSections/rent/RentItemEdit.tsx
src/leases/helpers.ts
src/leases/selectors.ts
src/leases/types.ts
src/oldDwellingsInHousingCompaniesPriceIndex/actions.ts
src/oldDwellingsInHousingCompaniesPriceIndex/constants.ts
src/oldDwellingsInHousingCompaniesPriceIndex/oldDwellingsInHousingCompaniesPriceIndex.spec.ts
src/oldDwellingsInHousingCompaniesPriceIndex/reducer.ts
src/oldDwellingsInHousingCompaniesPriceIndex/requests.ts
src/oldDwellingsInHousingCompaniesPriceIndex/saga.ts
src/oldDwellingsInHousingCompaniesPriceIndex/selectors.ts
src/oldDwellingsInHousingCompaniesPriceIndex/types.ts
src/root/createRootReducer.ts
src/root/createRootSaga.ts

These changes implement the feature of adding tasotarkistus to a rent that previously does not have it. 
The `old_dwellings_in_housing_companies_price_index` has to be fetched from the database through the API, and the best way to implement this in the MVJ-UI is to create a new reducer for it. It should fetch the latest data from the DB when the LeaseListPage is opened. That data is used for adding a tasotarkistus for the rent.
The `old_dwellings_in_housing_companies_price_index` is supposed to be shown only for A-typed leases, so there's filtering for that.
These changes depend on these changes in the API: https://github.com/City-of-Helsinki/mvj/pull/793

MVJ-421 Tasotarkistus Add New

---

.vscode/launch.example.json

Allows you to debug inside VS Code, if you prefer that over browser tools.

Add launch configuration for VS Code internal debugger

---

src/leases/components/LeaseListPage.tsx
src/leases/components/LeasePage.tsx

This fixes the bug that prevents the user from adding tasotarkistus if they refresh the browser when a single lease is opened. Now the `oldDwellingsInHousingCompaniesPriceIndex` is fetched when the LeasePage is loaded so that it can be used for adding tasotarkistus if needed.

bugfix: not possible to add tasotarkistus if page refreshed in single lease view

---

src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndex.tsx
src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndexEdit.tsx
src/leases/enums.ts

Add two more info balls to the tasotarkistus section: start date and review days.

tasotarkistus: add ui data to start date and review days

---

src/leaseStatisticReport/helpers.ts
src/leaseStatisticReport/requests.ts

Report Excel link formulated the service unit query parameter like `service_unit=`, `service_unit=1`, and `service_unit=1,2`. API instead expects service unit IDs in query parameters in format `service_unit=1&service_unit=2`, or no parameter at all if no service units are selected.
Because now all report payloads align with the same format, there is no more need to separately fix the service unit param in the payload.

MVJ-565 Fix service unit ids in report query params

---

src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndex.tsx
src/leases/components/leaseSections/rent/OldDwellingsInHousingCompaniesPriceIndexEdit.tsx
src/leases/components/leaseSections/rent/RentItem.tsx
src/leases/components/leaseSections/rent/RentItemEdit.tsx
src/leases/enums.ts
src/leases/helpers.ts
src/leases/types.ts

Previously, tasotarkistus type for rent was named as `old_dwellings_in_housing_companies_price_index_type`, but in this change, it is renamed as `periodic_rent_adjustment_type`.
The related API changes are here: https://github.com/City-of-Helsinki/mvj/pull/801

rename tasotarkistus type variables

---

src/auditLog/helpers.ts
src/components/auditLog/AuditLogTableItemChange.tsx

Include support for areasearches and plotsearches in the auditlog view, to view the change fields.
Corresponding backend changes: https://github.com/City-of-Helsinki/mvj/pull/805

MVJ-214 auditlog: include areasearch and plotsearch

---

src/leases/components/leaseSections/rent/BasisOfRent.tsx

I documented the issues with calculating basis of rent values in the UI code.
There is a list of values that, instead of being calculated in the UI component, could be calculated and returned in an API response instead. This could simplify the UI code, and put the calculation of these values in a proper place, where there could be a single source of truth for these values.
The refactoring is a complex operation and, after discussing with the PM, should be carried out when the focus of the sprint is on billing logic and related topics.

Document issues with calculating basis of rent values in the UI

---

.github/workflows/sonarcloud.yml

"Warning: This action is deprecated and will be removed in a future release. Please use the sonarqube-scan-action action instead. The sonarqube-scan-action is a drop-in replacement for this action."

replace sonarcloud action with sonarqube drop-in replacement

---

src/areaSearch/components/AreaSearchApplicationEdit.tsx
src/areaSearch/components/AreaSearchApplicationListPage.tsx
src/areaSearch/components/EditAreaSearchPreparerForm.tsx
src/areaSearch/helpers.ts
vite.config.js

The requested change was implemented, but includes a bug: preparer is unset even if nothing is changed in the form.
This bug was present in the list view editing modal already, but now added to the areasearch details edit form. TODO

MVJ-203 Unselect areasearch preparer when lessor is changed

---

src/leaseStatisticReport/components/LeaseInvoicingConfirmationReport.tsx
src/leaseStatisticReport/enums.ts
src/leaseStatisticReport/helpers.ts

Show `subvention_euros_per_year` (`Subventio euroina / vuosi`) in 3 decimals, as it is in the Vuokrat tab.
Add enums to handle special cases of rendering certain field values.
Related API changes: https://github.com/City-of-Helsinki/mvj/pull/873

statistic report: 3 decimals for subvention_amount

---

src/components/address-search/AddressSearchInput.tsx

Behavior was that onblur this component sets its value from state.value. And if on initialization the value in state is `""`, it will always remove whatever WAS selected in the component, once user exits the focus.
Particularly this is a problem when users try to copy-paste.

set state.value to prop.selected in AreaSearchInput

---

src/areaSearch/components/AreaSearchApplication.tsx

it is a normal use case not to have geometry, as it can be also described in a textfield instead of marking it on the map

fix areasearch page to work without geometry

---

src/leases/components/createLease/CreateLeaseForm.tsx
src/leases/enums.ts
src/leases/helpers.ts
src/leases/saga.ts
src/leases/types.ts

When creating a lease from an area search application, create a link from the lease to the area search application so that it shows on the lease history in the summary tab view.
These changes are dependent on this fix in the field permissions: https://github.com/City-of-Helsinki/mvj/pull/899

MVJ-840 link lease to area search application

---

src/creditDecision/components/SearchForm.tsx

By removing the empty `subscription` object (and thus enabling subscription), the form now re-renders on changes. Secondly, make `values.contact_type` as conditionally chained, we ensure that there will be no error in case that the values object happens to be undefined.

credit decision search form: fix rendering issue

---

.github/workflows/test.yml
.yarnrc
Dockerfile.dev

This helps avoid accidentally installing poisoned dependencies, especially in local environments.
Next step would be to pin every dependency to exact version, instead of allowing "compatible commits" with `^`.

Freeze lockfile for installs

---

src/components/form/final-form/FieldTypeDatePicker.tsx

happened due to conversion to isodate as date timezone was something else. this code was added as interim fix during form migration but should not have been left in place

fix issue of selected dates appearing as -1 date
